package com.funstill.generator.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.funstill.generator.greendao.entity.DialogData;
import com.funstill.generator.greendao.entity.MessageData;
import com.funstill.generator.greendao.entity.UserData;

import com.funstill.generator.greendao.dao.DialogDataDao;
import com.funstill.generator.greendao.dao.MessageDataDao;
import com.funstill.generator.greendao.dao.UserDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dialogDataDaoConfig;
    private final DaoConfig messageDataDaoConfig;
    private final DaoConfig userDataDaoConfig;

    private final DialogDataDao dialogDataDao;
    private final MessageDataDao messageDataDao;
    private final UserDataDao userDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dialogDataDaoConfig = daoConfigMap.get(DialogDataDao.class).clone();
        dialogDataDaoConfig.initIdentityScope(type);

        messageDataDaoConfig = daoConfigMap.get(MessageDataDao.class).clone();
        messageDataDaoConfig.initIdentityScope(type);

        userDataDaoConfig = daoConfigMap.get(UserDataDao.class).clone();
        userDataDaoConfig.initIdentityScope(type);

        dialogDataDao = new DialogDataDao(dialogDataDaoConfig, this);
        messageDataDao = new MessageDataDao(messageDataDaoConfig, this);
        userDataDao = new UserDataDao(userDataDaoConfig, this);

        registerDao(DialogData.class, dialogDataDao);
        registerDao(MessageData.class, messageDataDao);
        registerDao(UserData.class, userDataDao);
    }
    
    public void clear() {
        dialogDataDaoConfig.clearIdentityScope();
        messageDataDaoConfig.clearIdentityScope();
        userDataDaoConfig.clearIdentityScope();
    }

    public DialogDataDao getDialogDataDao() {
        return dialogDataDao;
    }

    public MessageDataDao getMessageDataDao() {
        return messageDataDao;
    }

    public UserDataDao getUserDataDao() {
        return userDataDao;
    }

}
